### ISSUE TITLE
question about data/FBPase_dummy.train.tab

### ISSUE THREAD

**Issue by bright2311** [Asplund-Samuelsson/furee#10]
Hello. 
Could you introduce more about the questions below:

How do you get the kos in data/FBPase_KOs.txt？

How do you get the data/FBPase_dummy.train.tab for top model trainning?

Thank you.

**Comment by Asplund-Samuelsson** [comment]
The KOs in `data/FBPase_KOs.txt` were selected manually based on knowledge and the research focus. The origin of `data/FBPase_dummy.train.tab` is explained [here](https://github.com/Asplund-Samuelsson/furee#evaluation-of-a-top-model).

**Comment by bright2311** [comment]
Thank you very much.
