### ISSUE TITLE
Question about preparation.sh

### ISSUE THREAD

**Issue by L2-Zhang** [Asplund-Samuelsson/furee#9]
Hello.Your implementation ia amazing.

But when  I run furee-master\source\preparation.sh, two errors come out:

> grep: results/FBPase/distance/train.filtered.fasta: No such file or directory
> cat: results/FBPase/distance/train.filtered.fasta: No such file or directory

In my opinion, the orginal problem may be from these lines：
> source/filter_hmmer_output.R \
> ${OUTDIR}/jackhmmer \
> ${OUTDIR}/jackhmmer/train.unfiltered.txt >> $LOGFILE 2>&1

Could you try it again and show me how to fix it?

Thank you very much.

**Comment by Asplund-Samuelsson** [comment]
It works fine on my computer. Have you installed all R libraries that are required?

Please post these log files so I can check what is actually not working for you:
```
results/FBPase/jackhmmer/jackhmmer.log
results/FBPase/cdhit/cdhit.log
results/FBPase/aa/aa.log
results/FBPase/distance/distance.log
results/FBPase/taxonomy/taxonomy.log
```

**Comment by bright2311** [comment]
Thank you for the quick reply.

I install the R libs,"foreach","doMC","tidyverse".

The logs are shown as below:

**results/FBPase/jackhmmer/jackhmmer.log**

> Sat Apr 16 04:09:07 UTC 2022
> jackhmmer --cpu 4 -N 5 --noali   --tblout results/FBPase/jackhmmer/jackhmmer.0.tblout.txt   results/FBPase/jackhmmer/targets.split-0.fasta   data/uniprot/uniprot.fasta   > >(grep -P '^#|^@' > results/FBPase/jackhmmer/jackhmmer.0.stdout.txt)   2> results/FBPase/jackhmmer/jackhmmer.0.error.txt
>   
> jackhmmer --cpu 4 -N 5 --noali   --tblout results/FBPase/jackhmmer/jackhmmer.1.tblout.txt   results/FBPase/jackhmmer/targets.split-1.fasta   data/uniprot/uniprot.fasta   > >(grep -P '^#|^@' > results/FBPase/jackhmmer/jackhmmer.1.stdout.txt)   2> results/FBPase/jackhmmer/jackhmmer.1.error.txt
>   
> jackhmmer --cpu 4 -N 5 --noali   --tblout results/FBPase/jackhmmer/jackhmmer.2.tblout.txt   results/FBPase/jackhmmer/targets.split-2.fasta   data/uniprot/uniprot.fasta   > >(grep -P '^#|^@' > results/FBPase/jackhmmer/jackhmmer.2.stdout.txt)   2> results/FBPase/jackhmmer/jackhmmer.2.error.txt
>   
> jackhmmer --cpu 4 -N 5 --noali   --tblout results/FBPase/jackhmmer/jackhmmer.3.tblout.txt   results/FBPase/jackhmmer/targets.split-3.fasta   data/uniprot/uniprot.fasta   > >(grep -P '^#|^@' > results/FBPase/jackhmmer/jackhmmer.3.stdout.txt)   2> results/FBPase/jackhmmer/jackhmmer.3.error.txt
>   
> jackhmmer --cpu 4 -N 5 --noali   --tblout results/FBPase/jackhmmer/jackhmmer.4.tblout.txt   results/FBPase/jackhmmer/targets.split-4.fasta   data/uniprot/uniprot.fasta   > >(grep -P '^#|^@' > results/FBPase/jackhmmer/jackhmmer.4.stdout.txt)   2> results/FBPase/jackhmmer/jackhmmer.4.error.txt
>   
> jackhmmer --cpu 4 -N 5 --noali   --tblout results/FBPase/jackhmmer/jackhmmer.5.tblout.txt   results/FBPase/jackhmmer/targets.split-5.fasta   data/uniprot/uniprot.fasta   > >(grep -P '^#|^@' > results/FBPase/jackhmmer/jackhmmer.5.stdout.txt)   2> results/FBPase/jackhmmer/jackhmmer.5.error.txt
>   
> jackhmmer --cpu 4 -N 5 --noali   --tblout results/FBPase/jackhmmer/jackhmmer.6.tblout.txt   results/FBPase/jackhmmer/targets.split-6.fasta   data/uniprot/uniprot.fasta   > >(grep -P '^#|^@' > results/FBPase/jackhmmer/jackhmmer.6.stdout.txt)   2> results/FBPase/jackhmmer/jackhmmer.6.error.txt
>   
> jackhmmer --cpu 4 -N 5 --noali   --tblout results/FBPase/jackhmmer/jackhmmer.7.tblout.txt   results/FBPase/jackhmmer/targets.split-7.fasta   data/uniprot/uniprot.fasta   > >(grep -P '^#|^@' > results/FBPase/jackhmmer/jackhmmer.7.stdout.txt)   2> results/FBPase/jackhmmer/jackhmmer.7.error.txt
>   
> source/preparation.sh: source/filter_hmmer_output.R: /usr/bin/env: bad interpreter: Permission denied
> Traceback (most recent call last):
>   File "source/filter_fasta_by_id.py", line 12, in <module>
>     for line in open(seqid_file):
> FileNotFoundError: [Errno 2] No such file or directory: 'results/FBPase/jackhmmer/train.unfiltered.txt'
> 

**results/FBPase/cdhit/cdhit.log**

> Fri Apr 15 10:52:26 UTC 2022
> ================================================================
> Program: CD-HIT, V4.7 (+OpenMP), Jul 01 2017, 08:43:07
> Command: cd-hit -c 1.0 -T 0 -M 28000 -i
>          results/FBPase/jackhmmer/train.unfiltered.fasta -o
>          results/FBPase/cdhit/train.unique.fasta
> 
> Started: Fri Apr 15 10:52:26 2022
> ================================================================
>                             Output                              
> ----------------------------------------------------------------
> total number of CPUs in the system is 2
> Actual number of CPUs to be used: 2
> 
> total seq: 0
> longest and shortest : 0 and 18446744073709551615
> Total letters: 0
> Sequences have been sorted
> 
> Approximated minimal memory consumption:
> Sequence        : 0M
> Buffer          : 2 X 10M = 20M
> Table           : 2 X 65M = 130M
> Miscellaneous   : 0M
> Total           : 151M
> 
> Table limit with the given memory limit:
> Max number of representatives: 4000000
> Max number of word counting entries: 3481041268
> 
> 
>         0  finished          0  clusters
> 
> Apprixmated maximum memory consumption: 151M
> writing new database
> writing clustering information
> program completed !
> 
> Total CPU time 0.13
> 

**results/FBPase/aa/aa.log**

> Fri Apr 15 10:52:26 UTC 2022

results/FBPase/distance/distance.log

> Fri Apr 15 10:52:26 UTC 2022
> Traceback (most recent call last):
>   File "source/levenshtein_distance.py", line 3, in <module>
>     from Levenshtein import distance as LD
> ModuleNotFoundError: No module named 'Levenshtein'
> Traceback (most recent call last):
>   File "source/lengths_of_sequences.py", line 26, in <module>
>     print(seqname + "\t" + str(n))
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
> source/preparation.sh: source/filter_sequences_by_length.R: /usr/bin/env: bad interpreter: Permission denied
> source/preparation.sh: source/filter_sequences_by_distance.R: /usr/bin/env: bad interpreter: Permission denied
> Traceback (most recent call last):
>   File "source/filter_fasta_by_id.py", line 12, in <module>
>     for line in open(seqid_file):
> FileNotFoundError: [Errno 2] No such file or directory: 'results/FBPase/distance/train.filtered.txt'

**results/FBPase/taxonomy/taxonomy.log**

> Sat Apr 16 04:17:44 UTC 2022
> grep: results/FBPase/distance/train.filtered.fasta: No such file or directory
> Loading NCBI names.dmp file.
> Loading NCBI nodes.dmp file.
> Analysing taxonomy and writing to outfile.
> Loading taxid-to-rank from nodes.dmp.
> source/preparation.sh: source/taxonomic_distribution_of_train.R: /usr/bin/env: bad interpreter: Permission denied
> 

Thank you very much.

**Comment by Asplund-Samuelsson** [comment]
I pushed a potential fix for the issue. The code is now calling the interpreters explicitly instead of relying on the shebang, which appears to be incompatible with some environments. Let me know if it works.

**Comment by bright2311** [comment]
I think it works while implementing the step of Prepare training data,because the file "${OUTDIR}/taxonomy/train.filtered.taxonomy.tab" is generated.
Is that right?

**Comment by Asplund-Samuelsson** [comment]
Yes, that file will not be successfully generated without files from the previous steps. I will close this issue now. Thank you for trying out the code and contributing to this improvement.

**Comment by L2-Zhang** [comment]
Thank you. I have run the git succsefully.
The git combines py, R and shell, which urges me to learn more.
I find a bug during running phate_fbpase_rubisco.R.
The error shows data/colours.txt has 19 items,but fbpase_taxonomy_file  and rubisco_taxonomy_file have only 13 columns.
I have delete some items in colours.txt. And it works in my environment.
You could try it.
